### ISSUE TITLE
Numeric fields load as str

### ISSUE THREAD

**Issue by kDmartel** [dashaub/espandas#1]
Hello,
I have an issue when I tried to visualize my data into kibana after upload it in ElasticSearch through this package. My numeric fields are converted in str because of line 83 espandas.py file. 
I have implemented a quick solution : delete this line and replace na by a string : 'Unknown'
I am working on a better solution : create a mapping and pass it as arg when index is created. 

What do you think of these solutions? Are you interested by my contribution to your project?

Kevin

**Comment by dashaub** [comment]
Yes, I would accept a PR that fixes this, particularly if it has unit tests.

**Comment by dashaub** [comment]
Fixed in #5
