### ISSUE TITLE
Incompatible with pandas > 0.21.0: AttributeError: 'DataFrame' object has no attribute 'reindex_axis'

### ISSUE THREAD

**Issue by vscodesync0815** [dashaub/espandas#2]
Using a pandas 0.25.3 dataframe the following error occurs:

File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/espandas/espandas.py", line 82, in es_write
    df = df.reindex_axis(sorted(df.columns), axis=1)
  File "/home/x/anaconda3/envs/x/lib/python3.7/site-packages/pandas/core/generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'reindex_axis'

Deprecated since version 0.21.0: Use reindex instead.

see:
https://pandas.pydata.org/pandas-docs/version/0.24/reference/api/pandas.DataFrame.reindex_axis.html

**Comment by ahoquegh** [comment]
Just open the espandas.py file and search/replace df.reindex_axis(.......) with df.reindex(......). You need to replace in two locations. That should make it work

**Comment by dashaub** [comment]
Fixed in https://github.com/dashaub/espandas/pull/4
