### ISSUE TITLE
Connect with a no localhost remote host with user and password

### ISSUE THREAD

**Issue by vibarco** [dashaub/espandas#3]
Hello,

i would like to know how to create a connection with espandas like this:

```
elk = Elasticsearch([{
    'host': '192.168.0.100',
    'port': '9200'
    }], http_auth=('elastic', 'changeme'))
```
Thanks

**Comment by dashaub** [comment]
@vibarco That should work by passing in as kwargs to the `Espandas` constructor.

**Comment by LeninGF** [comment]
It worked by making the following (in case yo:

> Hello,
> 
> i would like to know how to create a connection with espandas like this:
> 
> ```
> elk = Elasticsearch([{
>     'host': '192.168.0.100',
>     'port': '9200'
>     }], http_auth=('elastic', 'changeme'))
> ```
> 
> Thanks

What worked for me was:

```
from espandas import Espandas
INDEX = "myindex2021"
TYPE = '_doc'
esp = Espandas()
esp.client=es
esp.es_write(data_frame, INDEX, TYPE)
```

Where 

```
es = Elasticsearch(hosts='192.168.20.237:9200', 
                   http_auth=("user", "password"),
                  verify_certs=True)
```
